// Builds the ordered, per-slide metadata (kind/label/songId) shown next to
// each real slide thumbnail in the 편집기 (PPT editor) view's left panel.
// Every row here must line up 1:1 with the actual rendered slide at the same
// index, so counts come from the real generated byte buffers (via
// inspectDeckBytes) or from planSlides() — the exact function the real
// generator (buildPptx) uses — never from an estimate.
import type { Song } from './types';
import { planSlides } from './slidePlanner';

export type DeckOverviewKind =
  | 'front'
  | 'lyrics-title'
  | 'lyrics'
  | 'prayer'
  | 'bible'
  | 'sermon'
  | 'divider'
  | 'announcement'
  | 'back';

export interface DeckOverviewItem {
  id: string;
  kind: DeckOverviewKind;
  /** Main line, e.g. the song title or announcement title. */
  label: string;
  /** Secondary line, e.g. the first lyric line or "2/5". */
  subtitle?: string;
  /** For 'lyrics-title'/'lyrics' rows: which song this slide belongs to. */
  songId?: string;
}

/**
 * One song's overview rows (a title row, then one row per lyric slide), in
 * the exact order and grouping `planSlides()` produces — the same function
 * `buildPptx()` itself calls, so this can never drift from what's generated.
 */
export function songOverviewItems(song: Song): DeckOverviewItem[] {
  return planSlides(song).map((plan, i) => {
    const label = song.title.trim() || '(제목 없음)';
    return plan.kind === 'title'
      ? { id: `song-${song.id}-${i}`, kind: 'lyrics-title' as const, label, songId: song.id }
      : {
          id: `song-${song.id}-${i}`,
          kind: 'lyrics' as const,
          label,
          subtitle: (plan.lines ?? []).join(' / '),
          songId: song.id,
        };
  });
}

export interface DeckSegment {
  kind: DeckOverviewKind;
  /** The REAL slide count for this segment (from inspectDeckBytes or a fixed count like 1 for a single prayer slide). */
  count: number;
  labelAt: (index: number, count: number) => string;
  subtitleAt?: (index: number, count: number) => string | undefined;
}

/** Expand one uniform segment (Front, 기도, 성경 말씀, 설교, 광고, Back) into one overview row per real slide. */
export function expandDeckSegment(segment: DeckSegment): DeckOverviewItem[] {
  return Array.from({ length: segment.count }, (_, i) => ({
    id: `${segment.kind}-${i}`,
    kind: segment.kind,
    label: segment.labelAt(i, segment.count),
    subtitle: segment.subtitleAt?.(i, segment.count),
  }));
}
